// <auto-generated />
using Duber.WebSite.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Duber.WebSite.Migrations
{
    [DbContext(typeof(ReportingContext))]
    partial class ReportingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Reporting")
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Duber.WebSite.Models.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<string>("CardNumber");

                    b.Property<string>("CardType");

                    b.Property<DateTime>("Created");

                    b.Property<double?>("Distance");

                    b.Property<int>("DriverId");

                    b.Property<string>("DriverName");

                    b.Property<TimeSpan?>("Duration");

                    b.Property<DateTime?>("Ended");

                    b.Property<decimal?>("Fare");

                    b.Property<decimal?>("Fee");

                    b.Property<string>("From");

                    b.Property<Guid?>("InvoiceId");

                    b.Property<string>("Model");

                    b.Property<string>("PaymentMethod");

                    b.Property<string>("PaymentStatus");

                    b.Property<string>("Plate");

                    b.Property<DateTime?>("Started");

                    b.Property<string>("Status");

                    b.Property<string>("To");

                    b.Property<int>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
